//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAIDAChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class content_under_8000
    {
        public int id { get; set; }
        public int share_id { get; set; }
        public byte[] file_data { get; set; }
    }
}
