//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAIDAChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_members
    {
        public System.Guid group_id { get; set; }
        public System.Guid member_id { get; set; }
        public string allow_or_deny { get; set; }
    
        public virtual groups groups { get; set; }
    }
}
